### ISSUE TITLE
[Feature] Add support for Optifine format?

### ISSUE THREAD

**Issue by DitDitGitHub** [emilyalexandra/chime#1]
This would mean Optifine CIT support would be available for Sodium, which would be great.

**Comment by emilyalexandra** [comment]
Optifine CIT is not a format I'm at all interested in having support for, if I was interested in using that format, I would have just used Optifine. You'll find that Chime supports more than CIT and conversion to the format is mostly painless.

**Comment by UltraBlackLinux** [comment]
> Optifine CIT is not a format I'm at all interested in having support for, if I was interested in using that format, I would have just used Optifine. You'll find that Chime supports more than CIT and conversion to the format is mostly painless.

Even though I understand your thoughts, I would also like to see this. The problem with this mod, as well as NBT-textures, is, that there are no RPs supporting their formats. For resource packs like Vader's stacked items, the effort is just too high to change every file. I just don't use OF with fabric, since it's slow, dumb, and old.
I really hope for some mod dev to get CIT's working, it's pretty much one of the most useful features of OF.
Thanks!

**Comment by MithicSpirit** [comment]
> I would have just used Optifine

I personally use Sodium (with Indium for Fabric API support), which is not compatible with Optifine. I was hoping this mod would allow me to use regular texture pack's CIT textures with it but that is not the case as of now.

> You'll find that Chime supports more than CIT and conversion to the format is mostly painless.

While doing a conversion might be easy, it would depend on the license that the resource pack is distributed under. Depending on the texture pack this might be illicit to perform.

I understand that making a mod can be a lot of work but I wish you would reconsider not supporting Optifine CIT.

**Comment by emilyalexandra** [comment]
I am not going to support an ancient format that can only function in optifine because of layers on layers of hacks and breaking of conventions, efficiency, and reasonable code structure. CIT does not belong anywhere near vanilla, and Chime is specifically designed to be an extension of existing systems rather than a brand new wheel. I understand your concerns about licensing and the effort of a conversion process but CIT is both technologically challenging to a point where it's completely out of scope and supports conventions I ideologically oppose. I do not plan on rethinking this.

**Comment by MithicSpirit** [comment]
Alright, that is understandable. Thank you for the response!

**Comment by LambdAurora** [comment]
Additionally, OptiFine breaks Vanilla behavior very badly, this goes so badly that it can even affects data packs.

In modern Minecraft there's the concept of Identifiers, the rules are simple, not upper case, no space, only lowercase alphanumeric, `_` and `/` are allowed.

OptiFine breaks this rules by allowing spaces and uppercase characters, to ensure the capability to load OptiFine CIT it would require to break Vanilla as well, which I believe is a hard no from Emi.

I might be a bit harsh and very opinionated for the following bits but, to be honest? OptiFine formats need to die, they are a thing of the past, it's more precisely MCPatcher format, which is 11 years old and its format did not evolved much. How can you expect people to still support something that literally did not evolved much in 11 years **while the game had major refactors like 1.13**!
MCPatcher & OptiFine are stuck in the past, it's time to go forward.
If the pack you want to use is not working with Chime, I would suggest to kindly contact the pack authors about it.

**Comment by MithicSpirit** [comment]
Oh wow I was not aware that OF broke Vanilla behavior! Yeah then this definitely shouldn't be compatible with that lol.

**Comment by pooltoymae** [comment]
> You'll find that Chime supports more than CIT and conversion to the format is mostly painless.

Could you describe this process? I've looked at the wiki but unfortunately there's not enough info there for figuring out this conversion, especially if you don't develop resource packs yourself (yet). I'm fully up to learning but more documentation, especially on converting our favorite resource packs from optifine to this mod is sorely needed. Once I've learned the ins and outs of this mod from you and/or other contributors, I'd be more than happy to contribute to the development of more documentation.

**Comment by TheDrawingCoder-Gamer** [comment]
+1. I fully think that this proccess isn't described. I am trying to convert a resource pack but I have no idea where to start.

**Comment by TheDrawingCoder-Gamer** [comment]
Maybe we should make a new issue about documentation?

**Comment by emilyalexandra** [comment]
I'm not sure what in particular you find confusing about chime's format, it's a simple extension of the vanilla resource pack format, if you're familiar with that then chime should be extremely easy to work with.

**Comment by TheDrawingCoder-Gamer** [comment]
is there a link to a tutorial for the base game?

**Comment by TheDrawingCoder-Gamer** [comment]
I personally have figured it out but clarifying that it _needs_ to be in a overrides folder would help a lot

**Comment by emilyalexandra** [comment]
This is not the case, that is simply one of the ways you can make overrides work

**Comment by TheDrawingCoder-Gamer** [comment]
and now i don't understand how armor works. this is very confusing and the examples aren't enough

**Comment by pooltoymae** [comment]
> I'm not sure what in particular you find confusing about chime's format, it's a simple extension of the vanilla resource pack format, if you're familiar with that then chime should be extremely easy to work with.

Oh, it's just an extension of the vanilla format? That helps me figure out where to start when learning how to do this translation. Thanks!

**Comment by Kore-Development** [comment]
Could there be a tool that can convert existing Optifine resource packs to Chime resource packs, so you don't have to convert them manually for bigger resource packs?

**Comment by eljugador003** [comment]
What Kore-Developmet says could be really good way to kinda fix the problem Old optifine texture are causing to the new era of Minecraft, is it difficult to make a tool that does that?
