### ISSUE TITLE
Textures are not replaced when renaming an item using the cmi command

### ISSUE THREAD

**Issue by Niksette** [emilyalexandra/chime#13]
Textures are not replaced when renaming an item using the cmi command.
But works when renamed with anvil.
Outwardly, the names of the items are the same, the NBT tag is the same, but it still does not work.
Is it possible to fix this somehow from the side of the mod?

Command from Content Management Interface plugin:
/cmi itemname Niksette

![2021-06-25_10-48-26](https://user-images.githubusercontent.com/75724507/123389808-efd40580-d5a2-11eb-868d-6ac1b0118bf4.png)

![2021-06-25_10-47-44](https://user-images.githubusercontent.com/75724507/123389828-f4002300-d5a2-11eb-9b09-3644a8f11aa4.png)

![2021-06-25_10-47-59](https://user-images.githubusercontent.com/75724507/123389913-0a0de380-d5a3-11eb-9836-14d12d6b79e4.png)

![2021-06-25_10-48-11](https://user-images.githubusercontent.com/75724507/123389881-01b5a880-d5a3-11eb-8fdf-2c8298cea44c.png)

Thank you in advance!

**Comment by emilyalexandra** [comment]
If the items are not rendering the same, I think your claim that the tag is the same is misplaced, can you show me both of the tags? and what happens if you use the name predicate instead of nbt? regex?

**Comment by Niksette** [comment]
You are right, NBT tags are really different, but I don't understand exactly how to solve this.

![2021-06-25_11-46-33](https://user-images.githubusercontent.com/75724507/123397526-2e6dbe00-d5ab-11eb-9a87-e7706321cc60.png)

![2021-06-25_11-46-23](https://user-images.githubusercontent.com/75724507/123397530-30d01800-d5ab-11eb-86d5-5352915b4624.png)

Initially, I used a predicate, when specifying a regular expression, the result is also negative.
Now json looks like this:

![2021-06-25_11-45-56](https://user-images.githubusercontent.com/75724507/123397753-71c82c80-d5ab-11eb-9471-e2a6b6276c82.png)

**Comment by Niksette** [comment]
I found a solution in your discord server:
        {"predicate": {"display": {"name": '{"text":"/.*(?i)Niksette*/"}'}}, "model": "chb:item/totem/totem_niksette"},

Thank you very much for the help!
