### ISSUE TITLE
 Is it possible to create a custom entity model/texture with a name tag using Chime?

### ISSUE THREAD

**Issue by sasha066** [emilyalexandra/chime#8]
If yes, can you please give an example?

**Comment by supsm** [comment]
you should go to the [discord](https://discord.gg/T2PuD9RTWV) for help, there are example packs as well
and to answer your question, no. I believe [varied mob textures](https://www.curseforge.com/minecraft/mc-mods/varied-mob-textures) can do that though

**Comment by emilyalexandra** [comment]
chime does not work for for entity textures, it is for items unfortunately
