### ISSUE TITLE
Crash with Requiem installed

### ISSUE THREAD

**Issue by Pyrofab** [emilyalexandra/chime#9]
NPE in ModelOverride code: [crash-2021-05-17_18.27.53-client.txt](https://gist.github.com/Pyrofab/3fd19c851a1753e002e4b2d00db611a3)

I believe it may be related to this mixin, which dynamically adds a new override to enchanted books: [ModelLoaderMixin.java](https://github.com/Ladysnake/Requiem/blob/1.7.6/src/main/java/ladysnake/requiem/mixin/client/humanity/ModelLoaderMixin.java#L57)

Not sure what it is exactly though, there is nothing obvious in Chime's code that could trip.

**Comment by FourInchKnife** [comment]
@Pyrofab I ran in to this issue too. It was causing quite the headache. I now have to either remove requiem or search through a bunch of mods to find which one has chime bundled...

**Comment by Pyrofab** [comment]
That's rather unexpected now, as requiem *depends* on Chime. Could you share your crash report ?

**Comment by FourInchKnife** [comment]
> That's rather unexpected now, as requiem _depends_ on Chime. Could you share your crash report ?

I might have an older version of Requiem... I’m going to update and see if it still crahses. The crash was an NPE when loading the models of some items in the inventory.

**Comment by FourInchKnife** [comment]
Yeah, this is Requiem's fault. The latest version fixes it (and also bundles chime)!

**Comment by FourInchKnife** [comment]
@Pyrofab after I updated, is fixed the issue. I think it’s time to close this one.

**Comment by Pyrofab** [comment]
Right, I guess it's not necessary to fix this issue anymore. Would still have been nice to know what went wrong, but there's a bunch of more exciting things to do with our time.
